import React, { useState, useEffect } from 'react';
import { useSearchParams } from 'react-router-dom';
import { useQuery, useMutation } from '@tanstack/react-query';
import { quizService } from '../services/quizService';
import { newsService } from '../services/newsService';
import { 
  Sparkles, Trophy, HelpCircle, ArrowRight, RotateCcw, Loader2, ChevronDown, CheckCircle2, BookOpen, Clock 
} from 'lucide-react';
import confetti from 'canvas-confetti';

export const QuizArenaPage = () => {
  const [searchParams, setSearchParams] = useSearchParams();
  const [isDropdownOpen, setIsDropdownOpen] = useState(false);
  
  // 1. Fetch available articles for quiz selection
  const { data: feedData } = useQuery({
    queryKey: ['newsFeedForQuiz'],
    queryFn: async () => {
      const res = await newsService.getNewsFeed('all', '', 0, 20);
      return res.data?.content || [];
    },
  });

  const articles = feedData || [];
  
  // Active article ID
  const paramArticleId = searchParams.get('articleId');
  const [activeArticleId, setActiveArticleId] = useState(paramArticleId || null);

  useEffect(() => {
    if (paramArticleId) {
      setActiveArticleId(paramArticleId);
    } else if (articles.length > 0 && !activeArticleId) {
      setActiveArticleId(articles[0].id);
    }
  }, [articles, paramArticleId, activeArticleId]);

  const [selectedAnswers, setSelectedAnswers] = useState({});
  const [isSubmitted, setIsSubmitted] = useState(false);

  // 2. Fetch or Generate AI Quiz for active selected article
  const { data: quiz, isLoading, isError, refetch, isFetching } = useQuery({
    queryKey: ['quiz', activeArticleId],
    queryFn: async () => {
      if (!activeArticleId) return null;
      const res = await quizService.getOrGenerateQuiz(activeArticleId);
      return res.data;
    },
    enabled: !!activeArticleId,
  });

  // Submit Quiz Mutation
  const submitQuizMutation = useMutation({
    mutationFn: (answers) => quizService.submitQuiz(quiz.id, answers),
    onSuccess: (data) => {
      setIsSubmitted(true);
      if (data.data.passed) {
        confetti({ particleCount: 100, spread: 100, origin: { y: 0.5 } });
      }
    },
  });

  const handleSelectArticle = (artId) => {
    setActiveArticleId(artId);
    setSearchParams({ articleId: artId });
    setIsDropdownOpen(false);
    setSelectedAnswers({});
    setIsSubmitted(false);
    submitQuizMutation.reset();
  };

  const handleSelectOption = (questionId, optionLetter) => {
    if (isSubmitted) return;
    setSelectedAnswers((prev) => ({ ...prev, [questionId]: optionLetter }));
  };

  const handleSubmit = () => {
    if (!quiz?.questions) return;
    // Backend expects a Map<Long, String> which maps questionId to selectedOption
    // Our selectedAnswers state is exactly that: { [questionId]: 'A' }
    submitQuizMutation.mutate(selectedAnswers);
  };

  const handleReset = () => {
    setSelectedAnswers({});
    setIsSubmitted(false);
    submitQuizMutation.reset();
  };

  const activeArticle = articles.find((a) => String(a.id) === String(activeArticleId));
  const result = submitQuizMutation.data?.data;
  const hasQuestions = quiz?.questions && quiz.questions.length > 0;

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-10 animate-fade-in font-sans">
      
      {/* Header Banner & Article Selector */}
      <div className="space-y-6">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 border-b border-gray-500/20 pb-6">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <h1 className="text-3xl sm:text-4xl font-black tracking-tight font-serif">
                AI Quiz Arena
              </h1>
              <Sparkles className="w-6 h-6 theme-accent-text" />
            </div>
            <p className="opacity-70 font-medium">
              Real-time comprehension quizzes generated by Google Gemini AI.
            </p>
          </div>

          <div className="flex items-center gap-2 px-4 py-2 rounded-full glass-panel text-xs font-bold border border-gray-500/20">
            <BookOpen className="w-4 h-4 theme-accent-text" />
            <span className="uppercase tracking-wider">Interactive Reader Test</span>
          </div>
        </div>

        {/* Custom Article Selection Box */}
        {articles.length > 0 && (
          <div className="relative">
            <label className="block text-xs font-bold opacity-70 uppercase tracking-wider mb-2">
              Select Article to Quiz:
            </label>

            <button
              onClick={() => setIsDropdownOpen(!isDropdownOpen)}
              className="w-full glass-panel border border-gray-500/20 hover:theme-accent-border rounded-2xl px-5 py-4 text-sm font-bold shadow-sm transition-all flex items-center justify-between gap-4 text-left"
            >
              <div className="flex items-center gap-3 overflow-hidden">
                <span className="px-3 py-1 rounded-full text-[11px] font-black uppercase tracking-wider bg-gray-500/10 theme-accent-text shrink-0">
                  {activeArticle?.category || 'NEWS'}
                </span>
                <span className="truncate font-black">
                  {activeArticle?.title || 'Select an article to generate quiz...'}
                </span>
              </div>
              <ChevronDown className={`w-5 h-5 opacity-50 shrink-0 transition-transform duration-200 ${isDropdownOpen ? 'rotate-180' : ''}`} />
            </button>

            {/* Custom Interactive Article Selector Menu */}
            {isDropdownOpen && (
              <div className="absolute top-full left-0 right-0 mt-2 z-40 glass-panel border border-gray-500/20 rounded-2xl shadow-xl max-h-80 overflow-y-auto divide-y divide-gray-500/10 animate-fade-in p-2">
                {articles.map((art) => {
                  const isSelected = String(art.id) === String(activeArticleId);
                  return (
                    <div
                      key={art.id}
                      onClick={() => handleSelectArticle(art.id)}
                      className={`p-3.5 rounded-xl cursor-pointer transition-all flex items-center justify-between gap-3 ${
                        isSelected ? 'bg-gray-500/10 font-extrabold' : 'hover:bg-gray-500/10'
                      }`}
                    >
                      <div className="flex items-center gap-3 overflow-hidden">
                        <span className={`px-2.5 py-0.5 rounded-full text-[10px] font-black uppercase shrink-0 ${
                          isSelected ? 'theme-accent-bg text-white' : 'bg-gray-500/10 opacity-70'
                        }`}>
                          {art.category || 'NEWS'}
                        </span>
                        <span className={`text-xs font-bold truncate ${isSelected ? 'theme-accent-text' : 'opacity-90'}`}>
                          {art.title}
                        </span>
                      </div>
                      {isSelected && <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />}
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        )}
      </div>

      {/* Loading State */}
      {(isLoading || isFetching) && (
        <div className="p-16 rounded-3xl glass-card border-gray-500/20 text-center space-y-4 shadow-sm">
          <Loader2 className="w-10 h-10 theme-accent-text animate-spin mx-auto" />
          <div>
            <h3 className="text-lg font-black font-serif">Generating AI Quiz...</h3>
            <p className="opacity-70 text-sm font-medium mt-1">Google Gemini is crafting custom comprehension questions.</p>
          </div>
        </div>
      )}

      {/* Empty / Fallback State */}
      {!isLoading && !isFetching && (!quiz || !hasQuestions) && (
        <div className="p-16 rounded-3xl glass-card border-gray-500/20 text-center max-w-lg mx-auto my-8 space-y-5 shadow-sm">
          <HelpCircle className="w-14 h-14 theme-accent-text mx-auto" />
          <div>
            <h3 className="text-xl font-black font-serif">Ready to Quiz?</h3>
            <p className="opacity-70 text-sm font-medium mt-2 leading-relaxed">
              Click below to trigger AI multiple-choice quiz generation for the selected headline.
            </p>
          </div>
          <button
            onClick={() => refetch()}
            className="px-8 py-3.5 rounded-full theme-accent-bg text-white hover:opacity-90 text-sm font-bold shadow-md inline-flex items-center justify-center gap-2 transition-opacity"
          >
            <Sparkles className="w-4 h-4" />
            <span>Generate AI Quiz Now</span>
          </button>
        </div>
      )}

      {/* Active Quiz Card */}
      {!isLoading && !isFetching && quiz && hasQuestions && (
        <div className="p-8 sm:p-10 rounded-3xl glass-card shadow-sm space-y-10">
          
          {/* Article Quiz Header */}
          <div className="border-b border-gray-500/20 pb-6 space-y-3">
            <div className="flex items-center justify-between gap-3">
              <span className="text-[11px] font-black bg-gray-500/10 theme-accent-text px-3.5 py-1 rounded-full uppercase tracking-wider">
                {activeArticle?.category || 'News Quiz'}
              </span>
              <span className="text-xs font-bold opacity-70 bg-gray-500/10 px-3 py-1 rounded-full border border-gray-500/20">
                {quiz.questions.length} Multiple-Choice Questions
              </span>
            </div>
            <h2 className="text-xl sm:text-2xl font-black font-serif leading-snug">
              {quiz.title || activeArticle?.title}
            </h2>
          </div>

          {/* Questions List */}
          <div className="space-y-10">
            {quiz.questions.map((q, qIdx) => {
              const selected = selectedAnswers[q.id];
              const qResult = result?.questionResults?.find((r) => r.questionId === q.id);

              return (
                <div key={q.id} className="space-y-4">
                  <div className="flex items-start gap-3">
                    <span className="w-8 h-8 rounded-full glass-panel opacity-90 font-black text-sm flex items-center justify-center shrink-0">
                      {qIdx + 1}
                    </span>
                    <h3 className="text-lg font-black leading-snug font-serif pt-1">
                      {q.questionText}
                    </h3>
                  </div>

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3.5 pt-2">
                    {[
                      { key: 'A', text: q.optionA },
                      { key: 'B', text: q.optionB },
                      { key: 'C', text: q.optionC },
                      { key: 'D', text: q.optionD },
                    ].map((opt) => {
                      const isChoice = selected === opt.key;
                      let optionStyle = 'glass-panel border border-gray-500/20 hover:theme-accent-border hover:opacity-100 opacity-90';

                      if (isChoice) {
                        optionStyle = 'theme-accent-bg text-white border-transparent shadow-md';
                      }

                      if (isSubmitted) {
                        if (opt.key === q.correctOption) {
                          optionStyle = 'bg-emerald-600 text-white border-emerald-600 font-bold shadow-md';
                        } else if (isChoice && !qResult?.isCorrect) {
                          optionStyle = 'bg-rose-600 text-white border-rose-600 shadow-md';
                        }
                      }

                      return (
                        <button
                          key={opt.key}
                          onClick={() => handleSelectOption(q.id, opt.key)}
                          className={`p-4 rounded-2xl text-left text-sm font-medium transition-all flex items-center justify-between shadow-sm ${optionStyle}`}
                        >
                          <span className="leading-snug"><strong className="mr-2 text-sm">{opt.key}.</strong> {opt.text}</span>
                        </button>
                      );
                    })}
                  </div>

                  {/* AI Explanation Drawer */}
                  {isSubmitted && q.explanation && (
                    <div className="p-5 rounded-2xl bg-gray-500/10 border border-gray-500/20 text-sm opacity-90 leading-relaxed font-medium">
                      <strong className="theme-accent-text font-bold flex items-center gap-2 mb-2 uppercase tracking-wider text-xs">
                        <Sparkles className="w-3.5 h-3.5" /> AI Explanation
                      </strong>
                      {q.explanation}
                    </div>
                  )}
                </div>
              );
            })}
          </div>

          {/* Submit / Results Actions */}
          <div className="pt-8 border-t border-gray-500/20 flex items-center justify-between">
            {!isSubmitted ? (
              <button
                onClick={handleSubmit}
                disabled={Object.keys(selectedAnswers).length < quiz.questions?.length}
                className="w-full py-4 rounded-full theme-accent-bg text-white font-bold text-sm shadow-md disabled:opacity-50 hover:opacity-90 flex items-center justify-center gap-2 transition-opacity"
              >
                <span>Submit & Grade Quiz</span>
                <ArrowRight className="w-4 h-4" />
              </button>
            ) : (
              <div className="flex flex-col sm:flex-row items-center justify-between gap-4 w-full">
                <div className="flex items-center gap-3">
                  <div className="w-12 h-12 rounded-full theme-accent-bg flex items-center justify-center shadow-md">
                    <Trophy className="w-6 h-6 text-white" />
                  </div>
                  <div>
                    <h3 className="text-xl font-black font-serif">
                      Score: {result?.score} / {quiz.questions.length}
                    </h3>
                    <p className="text-sm font-bold opacity-70">
                      {result?.passed ? 'Great job! Streak extended. 🔥' : 'Keep practicing! Review the explanations above.'}
                    </p>
                  </div>
                </div>
                
                <button
                  onClick={handleReset}
                  className="px-6 py-3 rounded-full bg-gray-500/10 hover:bg-gray-500/20 text-sm font-bold shadow-sm inline-flex items-center gap-2 transition-colors w-full sm:w-auto justify-center"
                >
                  <RotateCcw className="w-4 h-4" />
                  <span>Try Again</span>
                </button>
              </div>
            )}
          </div>

        </div>
      )}

    </div>
  );
};
